name: CI-CD-K3s

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:latest .

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to k3s
        shell: bash
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl get nodes
          kubectl apply -f k8s/
          kubectl set image deployment/devops-app devops-container=${{ secrets.DOCKER_USERNAME }}/devops-app:latest

